#include "Mochi.h"

int mochiFrame = 0;

void sendBuffer(U8G2_SSD1306_128X64_NONAME_F_HW_I2C* display){
	display->clearBuffer();					// clear the internal memory
	display->drawXBMP(0, 0, 128, 64, epd_bitmap_allArray[mochiFrame]); // draw fullscreen image generated by image2cpp website
	display->sendBuffer();					// transfer internal memory to the display
}

void drawMochiFrame(U8G2_SSD1306_128X64_NONAME_F_HW_I2C* display) { // main loop
	mochiFrame = 0;

	do{
		sendBuffer(display);
		taskYIELD();
	}
	
	while(90 > ++mochiFrame); // increase the mochiFrame number
}